[package]
name = "wave"
version = "1.0.0"
authors = ["Silas Berger <silas.berger@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.7"
wav = "0.3.0"